# --- !Ups
CREATE TABLE PET (
  ID        BIGINT      NOT NULL AUTO_INCREMENT,
  TYPE      VARCHAR(32) NOT NULL,
  NAME      VARCHAR(32) NOT NULL,
  GENDER    VARCHAR(8)  NOT NULL,
  TIMESTAMP TIMESTAMP   NOT NULL,
  PRIMARY KEY (id)
);